# Generated by Django 3.1.6 on 2021-02-06 15:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210205_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='guests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=22),
        ),
    ]
