# Generated by Django 3.1.6 on 2021-02-15 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210206_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedguests',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createevent',
            name='guests',
            field=models.CharField(max_length=100),
        ),
    ]
