# Generated by Django 3.1.6 on 2021-02-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20210215_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createevent',
            name='guests',
        ),
        migrations.AddField(
            model_name='createevent',
            name='guests',
            field=models.ManyToManyField(to='Users.InvitedGuests'),
        ),
    ]
