# Generated by Django 3.1.6 on 2021-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210224_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('identificationnumber', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100)),
                ('county', models.CharField(choices=[('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya')], default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='invitedguests',
            name='county',
        ),
        migrations.RemoveField(
            model_name='invitedguests',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='invitedguests',
            name='phonenumber',
        ),
    ]
