# Generated by Django 3.1.6 on 2021-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20210224_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestregistration',
            name='reservation',
            field=models.CharField(choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('Normal', 'Normal')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='', max_length=100),
        ),
    ]
