# Generated by Django 3.1.6 on 2021-02-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20210226_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitesOnlyRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='', max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('identificationnumber', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100)),
                ('county', models.CharField(choices=[('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya')], default='', max_length=100)),
                ('reservation', models.CharField(choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('Normal', 'Normal')], default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='guestregistration',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='guestregistration',
            name='title',
        ),
    ]
