# Generated by Django 3.1.7 on 2021-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20210305_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='eventtype',
            field=models.CharField(choices=[('', 'Select Gender'), ('Public Event', 'Public Event'), ('Invites Only', 'Invites Only')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='county',
            field=models.CharField(choices=[('', 'Select County'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitedguests',
            name='guestrole',
            field=models.CharField(choices=[('', 'Select Role'), ('Guest of Honour', 'Guest of Honour'), ('Main Speaker', 'Main Speaker'), ('Attendee', 'Attendee')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitedguests',
            name='guesttitle',
            field=models.CharField(choices=[('', 'Select Title'), ('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitesonlyregistration',
            name='county',
            field=models.CharField(choices=[('', 'Select County'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitesonlyregistration',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitesonlyregistration',
            name='reservation',
            field=models.CharField(choices=[('', 'Select Reservation'), ('VVIP', 'VVIP'), ('VIP', 'VIP'), ('Normal', 'Normal')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitesonlyregistration',
            name='title',
            field=models.CharField(choices=[('', 'Select Title'), ('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='', max_length=100),
        ),
    ]
