# Generated by Django 3.1.7 on 2021-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20210305_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createevent',
            old_name='created_by',
            new_name='eventorganizer',
        ),
        migrations.AlterField(
            model_name='createevent',
            name='eventtype',
            field=models.CharField(choices=[('', 'Select Event Type'), ('Public Event', 'Public Event'), ('Invites Only', 'Invites Only')], default='', max_length=100),
        ),
    ]
