# Generated by Django 3.1.7 on 2021-03-05 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0016_auto_20210305_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createevent',
            name='eventorganizer',
        ),
        migrations.AddField(
            model_name='createevent',
            name='event_organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
