# Generated by Django 3.1.7 on 2021-03-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_invitedguests_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createevent',
            name='guests',
        ),
        migrations.AddField(
            model_name='createevent',
            name='guests',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Users.invitedguests'),
            preserve_default=False,
        ),
    ]
