# Generated by Django 3.1.7 on 2021-03-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_auto_20210305_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='guests',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.invitedguests'),
        ),
    ]
