# Generated by Django 3.1.7 on 2021-03-05 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0022_auto_20210305_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='createevent',
            name='guests',
        ),
        migrations.AddField(
            model_name='createevent',
            name='guests',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.invitedguests'),
        ),
        migrations.AlterField(
            model_name='invitedguests',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
