# Generated by Django 3.1.7 on 2021-03-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_auto_20210306_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestregistration',
            name='event_applied_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.createevent'),
        ),
    ]
