# Generated by Django 3.1.7 on 2021-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_guestregistration_event_applied_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestregistration',
            name='event_applied_for',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
