# Generated by Django 3.1.7 on 2021-03-06 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0028_auto_20210306_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitesonlyregistration',
            name='event_applied_for',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invitesonlyregistration',
            name='event_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
