# Generated by Django 3.1.7 on 2021-03-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0029_auto_20210306_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='bio', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default='2020-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('', 'Select your city'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='contact', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(choices=[('', 'Select County'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('', 'Select your Religion'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Bahai', 'Bahai'), ('Jew', 'Jew')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
