# Generated by Django 3.1.6 on 2021-02-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventtype',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
